In [2]:
%pip install pandas
import pandas as pd

In [3]:
marks = pd.Series([80,90,75,65])

print(marks)

0    80
1    90
2    75
3    65
dtype: int64

In [4]:
df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [4]:
import pandas as pd
data = {
    "Name": ["Ayukt", "Pinkee", "Arushi"],
    "Age": [18, 19, 20],
    "City": ["Lucknow", "Basti", "Sultanpur"]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City
0   Ayukt   18    Lucknow
1  Pinkee   19      Basti
2  Arushi   20  Sultanpur

In [6]:
data = {
    "Name": ["Ayukt", "Pinkee", "Arushi"],
    "Age": [18, 19, 20],
    "City": ["Lucknow", "Basti", "Sultanpur"]
}

df = pd.DataFrame(data)
print(df)

print(df.head())
print(df.tail())
print(df.shape)

     Name  Age       City
0   Ayukt   18    Lucknow
1  Pinkee   19      Basti
2  Arushi   20  Sultanpur
     Name  Age       City
0   Ayukt   18    Lucknow
1  Pinkee   19      Basti
2  Arushi   20  Sultanpur
     Name  Age       City
0   Ayukt   18    Lucknow
1  Pinkee   19      Basti
2  Arushi   20  Sultanpur
(3, 3)

In [7]:
import pandas as pd

# Create a 50x100 DataFrame using list comprehension
data = [[i * 100 + j for j in range(100)] for i in range(50)]
columns = [f"Col_{i+1}" for i in range(100)]

df = pd.DataFrame(data, columns=columns)

# Display head, tail, and shape
print("--- HEAD ---")
print(df.head())

print("\n--- TAIL ---")
print(df.tail())

print("\n--- SHAPE ---")
print(df.shape)

--- HEAD ---
   Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  ...  \
0      0      1      2      3      4      5      6      7      8       9  ...
1    100    101    102    103    104    105    106    107    108     109  ...
2    200    201    202    203    204    205    206    207    208     209  ...
3    300    301    302    303    304    305    306    307    308     309  ...
4    400    401    402    403    404    405    406    407    408     409  ...

   Col_91  Col_92  Col_93  Col_94  Col_95  Col_96  Col_97  Col_98  Col_99  \
0      90      91      92      93      94      95      96      97      98
1     190     191     192     193     194     195     196     197     198
2     290     291     292     293     294     295     296     297     298
3     390     391     392     393     394     395     396     397     398
4     490     491     492     493     494     495     496     497     498

   Col_100
0       99
1      199
2      299
3      399
4      499

[5 rows x 100 columns]

--- TAIL ---
    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
45   4500   4501   4502   4503   4504   4505   4506   4507   4508    4509
46   4600   4601   4602   4603   4604   4605   4606   4607   4608    4609
47   4700   4701   4702   4703   4704   4705   4706   4707   4708    4709
48   4800   4801   4802   4803   4804   4805   4806   4807   4808    4809
49   4900   4901   4902   4903   4904   4905   4906   4907   4908    4909

    ...  Col_91  Col_92  Col_93  Col_94  Col_95  Col_96  Col_97  Col_98  \
45  ...    4590    4591    4592    4593    4594    4595    4596    4597
46  ...    4690    4691    4692    4693    4694    4695    4696    4697
47  ...    4790    4791    4792    4793    4794    4795    4796    4797
48  ...    4890    4891    4892    4893    4894    4895    4896    4897
49  ...    4990    4991    4992    4993    4994    4995    4996    4997

    Col_99  Col_100
45    4598     4599
46    4698     4699
47    4798     4799
48    4898     4899
49    4998     4999

[5 rows x 100 columns]

--- SHAPE ---
(50, 100)

In [8]:
import pandas as pd

# List of student names to cycle through for 50 rows
sample_names = ["Rahul", "Priya", "Amit", "Neha", "Karan", "Riya", "Mohit", "Anjali", "Vivek", "Pooja"]

# Generate 50 rows of data (RollNo, Name, and 98 subject marks)
data = []
for i in range(50):
    roll_no = 101 + i
    name = sample_names[i % len(sample_names)]
    # Generate realistic marks (60 to 100) using basic arithmetic
    marks = [(60 + (i * 7 + j * 3) % 41) for j in range(98)]
    data.append([roll_no, name] + marks)

# Define 100 column names (RollNo + Name + Sub_1 to Sub_98)
columns = ["RollNo", "Name"] + [f"Sub_{j+1}" for j in range(98)]

# Create DataFrame
df = pd.DataFrame(data, columns=columns)

# Display head, tail, and shape
print("--- HEAD ---")
print(df.head())

print("\n--- TAIL ---")
print(df.tail())

print("\n--- SHAPE ---")
print(df.shape)

--- HEAD ---
   RollNo   Name  Sub_1  Sub_2  Sub_3  Sub_4  Sub_5  Sub_6  Sub_7  Sub_8  ...  \
0     101  Rahul     60     63     66     69     72     75     78     81  ...
1     102  Priya     67     70     73     76     79     82     85     88  ...
2     103   Amit     74     77     80     83     86     89     92     95  ...
3     104   Neha     81     84     87     90     93     96     99     61  ...
4     105  Karan     88     91     94     97    100     62     65     68  ...

   Sub_89  Sub_90  Sub_91  Sub_92  Sub_93  Sub_94  Sub_95  Sub_96  Sub_97  \
0      78      81      84      87      90      93      96      99      61
1      85      88      91      94      97     100      62      65      68
2      92      95      98      60      63      66      69      72      75
3      99      61      64      67      70      73      76      79      82
4      65      68      71      74      77      80      83      86      89

   Sub_98
0      64
1      71
2      78
3      85
4      92

[5 rows x 100 columns]

--- TAIL ---
    RollNo    Name  Sub_1  Sub_2  Sub_3  Sub_4  Sub_5  Sub_6  Sub_7  Sub_8  \
45     146    Riya     88     91     94     97    100     62     65     68
46     147   Mohit     95     98     60     63     66     69     72     75
47     148  Anjali     61     64     67     70     73     76     79     82
48     149   Vivek     68     71     74     77     80     83     86     89
49     150   Pooja     75     78     81     84     87     90     93     96

    ...  Sub_89  Sub_90  Sub_91  Sub_92  Sub_93  Sub_94  Sub_95  Sub_96  \
45  ...      65      68      71      74      77      80      83      86
46  ...      72      75      78      81      84      87      90      93
47  ...      79      82      85      88      91      94      97     100
48  ...      86      89      92      95      98      60      63      66
49  ...      93      96      99      61      64      67      70      73

    Sub_97  Sub_98
45      89      92
46      96      99
47      62      65
48      69      72
49      76      79

[5 rows x 100 columns]

--- SHAPE ---
(50, 100)

In [9]:
df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [10]:
df.head()

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88

In [11]:
df.head(2)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91

In [12]:
df.tail()

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [13]:
df.shape

(10, 1)

In [14]:
df.tail(2)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [16]:
df = pd.read_csv("record1.csv")

print(df)

    Col_1  Col_2  Col_3  Col_4  Col_5  Col_6  Col_7  Col_8  Col_9  Col_10  \
0      54     60      8     39     46     54     13     90     94      12
1      64     90     19     22     44      7     39     42     77      59
2      80     73     88     52     26     81     25     21     46      72
3      14     44     36     44      4     60     69      9     92      47
4       3     21     57      7     97     45     67      1     69      94
..    ...    ...    ...    ...    ...    ...    ...    ...    ...     ...
95     35     94     59     72     42     41     88     36     79      67
96     37     27     58     27     24     33     30     77     69      17
97     52     44     62     74     56     98     62      9     82       6
98     47     31     44     12     67     85     78     10     90      95
99     57     74     67     20     37     66     35     92     13      37

    ...  Col_41  Col_42  Col_43  Col_44  Col_45  Col_46  Col_47  Col_48  \
0   ...      38      56      22      28      13      31      18      96
1   ...      60      40      91       6      48       9      90      89
2   ...      23      30      87       8      48      36       8      70
3   ...      88      73      84      59      88      46      58      26
4   ...      91      12      78      69      41      28      87       1
..  ...     ...     ...     ...     ...     ...     ...     ...     ...
95  ...      98      48      39      79      85      37      41      92
96  ...      18      25      65     100      13      76      51      94
97  ...       9      61      35      68       6      16      51       2
98  ...      19      37      96      15      63       5      63      92
99  ...      84      62      18      75      24      37       4     100

    Col_49  Col_50
0       23      55
1       79       9
2        5      14
3       93      42
4       98      46
..     ...     ...
95       5     100
96      70      86
97      31      23
98      89      89
99      42      15

[100 rows x 50 columns]

In [17]:
df.head()

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,...,Col_41,Col_42,Col_43,Col_44,Col_45,Col_46,Col_47,Col_48,Col_49,Col_50
0,54,60,8,39,46,54,13,90,94,12,...,38,56,22,28,13,31,18,96,23,55
1,64,90,19,22,44,7,39,42,77,59,...,60,40,91,6,48,9,90,89,79,9
2,80,73,88,52,26,81,25,21,46,72,...,23,30,87,8,48,36,8,70,5,14
3,14,44,36,44,4,60,69,9,92,47,...,88,73,84,59,88,46,58,26,93,42
4,3,21,57,7,97,45,67,1,69,94,...,91,12,78,69,41,28,87,1,98,46

In [18]:
df.tail()

,Col_1,Col_2,Col_3,Col_4,Col_5,Col_6,Col_7,Col_8,Col_9,Col_10,...,Col_41,Col_42,Col_43,Col_44,Col_45,Col_46,Col_47,Col_48,Col_49,Col_50
95,35,94,59,72,42,41,88,36,79,67,...,98,48,39,79,85,37,41,92,5,100
96,37,27,58,27,24,33,30,77,69,17,...,18,25,65,100,13,76,51,94,70,86
97,52,44,62,74,56,98,62,9,82,6,...,9,61,35,68,6,16,51,2,31,23
98,47,31,44,12,67,85,78,10,90,95,...,19,37,96,15,63,5,63,92,89,89
99,57,74,67,20,37,66,35,92,13,37,...,84,62,18,75,24,37,4,100,42,15

In [21]:
df = pd.read_csv("record.csv")

print(df)
print(df.columns)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93
Index(['RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5'], dtype='str')

In [24]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [25]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 1 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5  10 non-null     str
dtypes: str(1)
memory usage: 112.0 bytes
None

In [28]:
print(df.describe())

       RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
count                                            10
unique                                           10
top      101     Rahul   78    85    90    88    76
freq                                              1

In [29]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [55000, 72000, 68000, 75000, 50000]
}

df = pd.DataFrame(data)
print(df)

    ID     Name Department  Salary
0  101    Alice         HR   55000
1  102      Bob         IT   72000
2  103  Charlie    Finance   68000
3  104    David         IT   75000
4  105      Eva  Marketing   50000

In [30]:
import pandas as pd

data = {
    "ID": list(range(101, 121)),
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Eva",
        "Frank", "Grace", "Henry", "Ivy", "Jack",
        "Karen", "Leo", "Mona", "Nathan", "Olivia",
        "Paul", "Quinn", "Rachel", "Steve", "Tina"
    ],
    "Department": [
        "HR", "IT", "Finance", "IT", "Marketing",
        "IT", "HR", "Finance", "Marketing", "IT",
        "Finance", "HR", "IT", "Marketing", "HR",
        "Finance", "IT", "Marketing", "HR", "Finance"
    ],
    "Salary": [
        55000, 72000, 68000, 75000, 50000,
        71000, 54000, 69000, 52000, 73000,
        67000, 56000, 74000, 51000, 58000,
        70000, 76000, 53000, 59000, 66000
    ]
}

df = pd.DataFrame(data)
print(df)

     ID     Name Department  Salary
0   101    Alice         HR   55000
1   102      Bob         IT   72000
2   103  Charlie    Finance   68000
3   104    David         IT   75000
4   105      Eva  Marketing   50000
5   106    Frank         IT   71000
6   107    Grace         HR   54000
7   108    Henry    Finance   69000
8   109      Ivy  Marketing   52000
9   110     Jack         IT   73000
10  111    Karen    Finance   67000
11  112      Leo         HR   56000
12  113     Mona         IT   74000
13  114   Nathan  Marketing   51000
14  115   Olivia         HR   58000
15  116     Paul    Finance   70000
16  117    Quinn         IT   76000
17  118   Rachel  Marketing   53000
18  119    Steve         HR   59000
19  120     Tina    Finance   66000

In [34]:
print(df["Name"])

0       Alice
1         Bob
2     Charlie
3       David
4         Eva
5       Frank
6       Grace
7       Henry
8         Ivy
9        Jack
10      Karen
11        Leo
12       Mona
13     Nathan
14     Olivia
15       Paul
16      Quinn
17     Rachel
18      Steve
19       Tina
Name: Name, dtype: str

In [36]:
print(df[["Name","Salary"]])

       Name  Salary
0     Alice   55000
1       Bob   72000
2   Charlie   68000
3     David   75000
4       Eva   50000
5     Frank   71000
6     Grace   54000
7     Henry   69000
8       Ivy   52000
9      Jack   73000
10    Karen   67000
11      Leo   56000
12     Mona   74000
13   Nathan   51000
14   Olivia   58000
15     Paul   70000
16    Quinn   76000
17   Rachel   53000
18    Steve   59000
19     Tina   66000

In [37]:
print(df.Name)

0       Alice
1         Bob
2     Charlie
3       David
4         Eva
5       Frank
6       Grace
7       Henry
8         Ivy
9        Jack
10      Karen
11        Leo
12       Mona
13     Nathan
14     Olivia
15       Paul
16      Quinn
17     Rachel
18      Steve
19       Tina
Name: Name, dtype: str

In [42]:
print(df.loc[0])

ID              101
Name          Alice
Department       HR
Salary        55000
Name: 0, dtype: object

In [41]:
print(df.iloc[1])

ID              102
Name            Bob
Department       IT
Salary        72000
Name: 1, dtype: object

In [43]:
print(df.iloc[2])

ID                103
Name          Charlie
Department    Finance
Salary          68000
Name: 2, dtype: object

In [44]:
print(df.iloc[0])

ID              101
Name          Alice
Department       HR
Salary        55000
Name: 0, dtype: object

In [45]:
df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [1]:
import pandas as pd
import numpy as np

# Creating a DataFrame with None and np.nan (null/missing values)
data = {
    "Name": ["Alice", "Bob", None, "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Lucknow", "Delhi", "Mumbai", None, "Kanpur"],
    "Score": [85.5, 90.0, np.nan, 88.0, None]
}

df = pd.DataFrame(data)

# Display the DataFrame
print("--- DataFrame ---")
print(df)

# Check for missing/null values (returns True where values are missing)
print("\n--- Missing Values Mask ---")
print(df.isna())

# Count missing values per column
print("\n--- Missing Values Count Per Column ---")
print(df.isna().sum())

--- DataFrame ---
    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

--- Missing Values Mask ---
    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

--- Missing Values Count Per Column ---
Name     1
Age      2
City     1
Score    2
dtype: int64

In [2]:
import pandas as pd

data = {
    "ID": list(range(101, 121)),
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Eva",
        "Frank", "Grace", "Henry", "Ivy", "Jack",
        "Karen", "Leo", "Mona", "Nathan", "Olivia",
        "Paul", "Quinn", "Rachel", "Steve", "Tina"
    ],
    "Department": [
        "HR", "IT", "Finance", "IT", "Marketing",
        "IT", "HR", "Finance", "Marketing", "IT",
        "Finance", "HR", "IT", "Marketing", "HR",
        "Finance", "IT", "Marketing", "HR", "Finance"
    ],
    "Salary": [
        55000, 72000, 68000, 75000, 50000,
        71000, 54000, 69000, 52000, 73000,
        67000, 56000, 74000, 51000, 58000,
        70000, 76000, 53000, 59000, 66000
    ]
}

df = pd.DataFrame(data)
print(df)

     ID     Name Department  Salary
0   101    Alice         HR   55000
1   102      Bob         IT   72000
2   103  Charlie    Finance   68000
3   104    David         IT   75000
4   105      Eva  Marketing   50000
5   106    Frank         IT   71000
6   107    Grace         HR   54000
7   108    Henry    Finance   69000
8   109      Ivy  Marketing   52000
9   110     Jack         IT   73000
10  111    Karen    Finance   67000
11  112      Leo         HR   56000
12  113     Mona         IT   74000
13  114   Nathan  Marketing   51000
14  115   Olivia         HR   58000
15  116     Paul    Finance   70000
16  117    Quinn         IT   76000
17  118   Rachel  Marketing   53000
18  119    Steve         HR   59000
19  120     Tina    Finance   66000

In [10]:
import numpy as np

df["Bonus"] = np.random.randint(0, 5000, size=len(df))
df["Total"] = df["Salary"] + df["Bonus"]

print(df.head())

    ID     Name Department  Salary  Bonus  Total
0  101    Alice         HR   55000   1579  56579
1  102      Bob         IT   72000   1674  73674
2  103  Charlie    Finance   68000   3605  71605
3  104    David         IT   75000   2210  77210
4  105      Eva  Marketing   50000   4435  54435

In [11]:
df.drop("Bonus", axis = 1)

     ID     Name Department  Salary  Total
0   101    Alice         HR   55000  56579
1   102      Bob         IT   72000  73674
2   103  Charlie    Finance   68000  71605
3   104    David         IT   75000  77210
4   105      Eva  Marketing   50000  54435
5   106    Frank         IT   71000  75286
6   107    Grace         HR   54000  54390
7   108    Henry    Finance   69000  71837
8   109      Ivy  Marketing   52000  54557
9   110     Jack         IT   73000  73572
10  111    Karen    Finance   67000  68846
11  112      Leo         HR   56000  58046
12  113     Mona         IT   74000  78313
13  114   Nathan  Marketing   51000  55847
14  115   Olivia         HR   58000  60800
15  116     Paul    Finance   70000  71657
16  117    Quinn         IT   76000  77355
17  118   Rachel  Marketing   53000  54131
18  119    Steve         HR   59000  59889
19  120     Tina    Finance   66000  67721

In [13]:
df["Location"] = "Lucknow"
print(df)

     ID     Name Department  Salary  Bonus  Total Location
0   101    Alice         HR   55000   1579  56579  Lucknow
1   102      Bob         IT   72000   1674  73674  Lucknow
2   103  Charlie    Finance   68000   3605  71605  Lucknow
3   104    David         IT   75000   2210  77210  Lucknow
4   105      Eva  Marketing   50000   4435  54435  Lucknow
5   106    Frank         IT   71000   4286  75286  Lucknow
6   107    Grace         HR   54000    390  54390  Lucknow
7   108    Henry    Finance   69000   2837  71837  Lucknow
8   109      Ivy  Marketing   52000   2557  54557  Lucknow
9   110     Jack         IT   73000    572  73572  Lucknow
10  111    Karen    Finance   67000   1846  68846  Lucknow
11  112      Leo         HR   56000   2046  58046  Lucknow
12  113     Mona         IT   74000   4313  78313  Lucknow
13  114   Nathan  Marketing   51000   4847  55847  Lucknow
14  115   Olivia         HR   58000   2800  60800  Lucknow
15  116     Paul    Finance   70000   1657  71657  Lucknow
16  117    Quinn         IT   76000   1355  77355  Lucknow
17  118   Rachel  Marketing   53000   1131  54131  Lucknow
18  119    Steve         HR   59000    889  59889  Lucknow
19  120     Tina    Finance   66000   1721  67721  Lucknow

In [24]:
# HR department ke rows filter karke Salary ka mean
hr_mean = df[df["Department"] == "HR"]["Salary"].mean()

print(hr_mean)

56400.0

In [27]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", None, "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Lucknow", "Delhi", "Mumbai", None, "Kanpur"],
    "Score": [85.5, 90.0, np.nan, 88.0, None]
}

df = pd.DataFrame(data)

print("--- DataFrame ---")
print(df)

print("\n--- Missing Values Mask ---")
print(df.isna())

print("\n--- Missing Values Count Per Column ---")
print(df.isna().sum())

--- DataFrame ---
    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

--- Missing Values Mask ---
    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

--- Missing Values Count Per Column ---
Name     1
Age      2
City     1
Score    2
dtype: int64

In [30]:
print(df.isnull())   #Null Value

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

In [29]:
print(df.isnull().sum())  #Count Missing Value

Name     1
Age      2
City     1
Score    2
dtype: int64

In [33]:
df.fillna(45)   #Fill The Missing Value

    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob  45.0    Delhi   90.0
2     45  30.0   Mumbai   45.0
3  David  22.0       45   88.0
4    Eva  45.0   Kanpur   45.0

In [35]:
df.fillna("Not Available")  #Fill All Missing Values

            Name            Age           City          Score
0          Alice           25.0        Lucknow           85.5
1            Bob  Not Available          Delhi           90.0
2  Not Available           30.0         Mumbai  Not Available
3          David           22.0  Not Available           88.0
4            Eva  Not Available         Kanpur  Not Available

In [38]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", None, "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Lucknow", "Delhi", "Mumbai", None, "Kanpur"],
    "Score": [85.5, 90.0, np.nan, 88.0, None]
}

df = pd.DataFrame(data)

print("--- DataFrame ---")
print(df)

print("\n--- Missing Values Mask ---")
print(df.isna())

print("\n--- Missing Values Count Per Column ---")
print(df.isna().sum())

--- DataFrame ---
    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

--- Missing Values Mask ---
    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

--- Missing Values Count Per Column ---
Name     1
Age      2
City     1
Score    2
dtype: int64

In [41]:
df.fillna({                     #Fill Different Missing Values
    "Score":45000,
    "Bonus":50000    
})

    Name   Age     City    Score
0  Alice  25.0  Lucknow     85.5
1    Bob   NaN    Delhi     90.0
2    NaN  30.0   Mumbai  45000.0
3  David  22.0      NaN     88.0
4    Eva   NaN   Kanpur  45000.0

In [43]:
df["Score"]=df["Score"].fillna(df["Score"].mean())
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2    NaN  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [45]:
df["Score"]=df["Score"].fillna(df["Score"].median())
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2    NaN  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [55]:
df["Name"]=df["Name"].fillna(df["Name"].mode())   #Mode
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2  David  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [54]:
df.dropna()   #replacing missing values

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
2  David  30.0   Mumbai  87.833333

In [56]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", None, "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Lucknow", "Delhi", "Mumbai", None, "Kanpur"],
    "Score": [85.5, 90.0, np.nan, 88.0, None]
}

df = pd.DataFrame(data)

print("--- DataFrame ---")
print(df)

print("\n--- Missing Values Mask ---")
print(df.isna())

print("\n--- Missing Values Count Per Column ---")
print(df.isna().sum())

--- DataFrame ---
    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

--- Missing Values Mask ---
    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

--- Missing Values Count Per Column ---
Name     1
Age      2
City     1
Score    2
dtype: int64

In [59]:
df = df.ffill()
print(df)

    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob  25.0    Delhi   90.0
2    Bob  30.0   Mumbai   90.0
3  David  22.0   Mumbai   88.0
4    Eva  22.0   Kanpur   88.0

In [3]:
import pandas as pd
df = pd.read_csv("company1.csv")

print(df)

    Employee ID             Name Department  Age  Salary
0       EMP0001       Kavya Jain  Marketing   24   83727
1       EMP0002  Krishna Agarwal    Finance   35   27795
2       EMP0003     Ishaan Gupta  Marketing   23  104343
3       EMP0004        Sai Yadav    Support   38  115790
4       EMP0005      Meera Gupta         HR   33  138216
..          ...              ...        ...  ...     ...
995     EMP0996      Ishaan Jain  Marketing   25  107937
996     EMP0997        Sai Singh    Finance   57   54278
997     EMP0998   Krishna Sharma  Marketing   33   61243
998     EMP0999        Sai Yadav         HR   50   55109
999     EMP1000       Riya Mehta         IT   32  142947

[1000 rows x 5 columns]

In [4]:
import pandas as pd
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

num_records = 1000

# Sample data pools
first_names = ["Aarav", "Ananya", "Rohan", "Priya", "Kabir", "Neha", "Rahul", "Isha", "Karan", "Sanya", 
               "Vikram", "Riya", "Amit", "Pooja", "Vivek", "Meera", "Arjun", "Kavya", "Krishna", "Sai"]
last_names = ["Sharma", "Verma", "Gupta", "Mehta", "Singh", "Kumar", "Patel", "Jain", "Agarwal", "Yadav"]
departments = ["HR", "IT", "Finance", "Marketing", "Sales", "Support", "Operations"]

# Generate base data
emp_ids = [f"EMP{i:04d}" for i in range(1, num_records + 1)]
names = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(num_records)]
depts = [np.random.choice(departments) for _ in range(num_records)]
ages = np.random.randint(22, 61, size=num_records).astype(float)
salaries = np.random.randint(30000, 150001, size=num_records).astype(float)

# Create DataFrame
df = pd.DataFrame({
    "Employee ID": emp_ids,
    "Name": names,
    "Department": depts,
    "Age": ages,
    "Salary": salaries
})

# Inject ~5% missing values (np.nan) randomly into Name, Department, Age, and Salary
for col in ["Name", "Department", "Age", "Salary"]:
    mask = np.random.rand(num_records) < 0.05
    df.loc[mask, col] = np.nan

# Save to CSV
df.to_csv("company_missing_data.csv", index=False)

# Display sample output and missing value summary
print("--- FIRST 10 ROWS ---")
print(df.head(10))

print("\n--- MISSING VALUE COUNT PER COLUMN ---")
print(df.isna().sum())

--- FIRST 10 ROWS ---
  Employee ID           Name  Department   Age    Salary
0     EMP0001    Rahul Mehta          HR  41.0   46199.0
1     EMP0002     Vivek Jain   Marketing  22.0  102827.0
2     EMP0003    Rahul Yadav     Finance  29.0  136464.0
3     EMP0004  Krishna Patel          HR  44.0   30112.0
4     EMP0005    Vikram Jain          HR  24.0  117051.0
5     EMP0006     Priya Jain         NaN  25.0   49581.0
6     EMP0007    Rohan Kumar     Support  46.0  144228.0
7     EMP0008    Ananya Jain          HR   NaN   89722.0
8     EMP0009     Riya Kumar  Operations  36.0  122036.0
9     EMP0010   Ananya Singh   Marketing  42.0  127562.0

--- MISSING VALUE COUNT PER COLUMN ---
Employee ID     0
Name           50
Department     41
Age            46
Salary         43
dtype: int64

In [5]:
print(df.isnull())

     Employee ID   Name  Department    Age  Salary
0          False  False       False  False   False
1          False  False       False  False   False
2          False  False       False  False   False
3          False  False       False  False   False
4          False  False       False  False   False
..           ...    ...         ...    ...     ...
995        False  False       False   True   False
996        False  False       False  False   False
997        False  False       False  False   False
998        False  False       False  False   False
999        False  False       False  False   False

[1000 rows x 5 columns]

In [6]:
print(df.isnull().sum())  #Count Missing Value

Employee ID     0
Name           50
Department     41
Age            46
Salary         43
dtype: int64